services:
  db:
    image: pgvector/pgvector:pg16
    container_name: postgres_db_with_vector
    environment:
      POSTGRES_DB: vector_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=trust"
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d vector_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      PG_HOST: my_postgres
      PG_PORT: 5432
      PG_DB: postgres
      PG_USER: postgres
      FILE_PATH: /app/test.doc
      PG_PASSWORD: postgres
    volumes:
      - .:/app
    working_dir: /app
    command: python main.py

volumes:
  pgdata: